# Generated by Django 3.0.8 on 2020-07-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Help',
        ),
    ]
