# Generated by Django 3.0.8 on 2020-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_delete_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='Countries',
            field=models.CharField(default='', max_length=60),
        ),
    ]
