# Generated by Django 3.0.8 on 2020-07-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200725_0503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
