# Generated by Django 3.0.8 on 2020-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headlines', models.CharField(max_length=3000)),
                ('Links', models.TextField(default='')),
                ('Countries', models.CharField(default='', max_length=60)),
                ('Date_Uploaded', models.TextField(default='')),
            ],
        ),
    ]
